// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Z8W7BKNiIFHuvNttJ5_kTo_sCbDj3o4',
    appId: '1:525920968814:web:49b4f5dcb3b3ce754d867f',
    messagingSenderId: '525920968814',
    projectId: 'flutter-update-945ca',
    authDomain: 'flutter-update-945ca.firebaseapp.com',
    databaseURL: 'https://flutter-update-945ca-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-update-945ca.appspot.com',
    measurementId: 'G-33MJ7G4ZWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWE3eWNWMjiEeidf9zo-NhTZrHKkZBfR4',
    appId: '1:525920968814:android:5880b0d5cb69b1f64d867f',
    messagingSenderId: '525920968814',
    projectId: 'flutter-update-945ca',
    databaseURL: 'https://flutter-update-945ca-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-update-945ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN8ai2r3KT91P93p-F2gO4FRQel7nZVbA',
    appId: '1:525920968814:ios:b275fc47db3e529e4d867f',
    messagingSenderId: '525920968814',
    projectId: 'flutter-update-945ca',
    databaseURL: 'https://flutter-update-945ca-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-update-945ca.appspot.com',
    iosClientId: '525920968814-fla7mps0dkn55gi2j12av4vg9853blqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN8ai2r3KT91P93p-F2gO4FRQel7nZVbA',
    appId: '1:525920968814:ios:b275fc47db3e529e4d867f',
    messagingSenderId: '525920968814',
    projectId: 'flutter-update-945ca',
    databaseURL: 'https://flutter-update-945ca-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-update-945ca.appspot.com',
    iosClientId: '525920968814-fla7mps0dkn55gi2j12av4vg9853blqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChat',
  );
}
